// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0qNv1A1EkK9KAW0GQGIGW_o4STktLHI',
    appId: '1:64942462685:web:5968a23224931098c7ad34',
    messagingSenderId: '64942462685',
    projectId: 'b-tech-math',
    authDomain: 'b-tech-math.firebaseapp.com',
    storageBucket: 'b-tech-math.appspot.com',
    measurementId: 'G-LF9X1YSB20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIYn6IebeXNv7gmBK3Po0RXjx7RyvRHlI',
    appId: '1:64942462685:android:c47a36127a686039c7ad34',
    messagingSenderId: '64942462685',
    projectId: 'b-tech-math',
    storageBucket: 'b-tech-math.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRj2JFvcDrKddYw7DUfZPW8MowEQW3Yxc',
    appId: '1:64942462685:ios:8ab53ab6923f5204c7ad34',
    messagingSenderId: '64942462685',
    projectId: 'b-tech-math',
    storageBucket: 'b-tech-math.appspot.com',
    iosClientId: '64942462685-8su9i3cr63nd5oe145mp3vga4lae8pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRj2JFvcDrKddYw7DUfZPW8MowEQW3Yxc',
    appId: '1:64942462685:ios:8ab53ab6923f5204c7ad34',
    messagingSenderId: '64942462685',
    projectId: 'b-tech-math',
    storageBucket: 'b-tech-math.appspot.com',
    iosClientId: '64942462685-8su9i3cr63nd5oe145mp3vga4lae8pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathApp',
  );
}
